# Generated by Django 5.1.3 on 2024-11-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=10)),
                ('dataRegisto', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
